# Generated by Django 2.1.5 on 2019-01-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_auto_20190125_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='title',
            field=models.CharField(default='Software Developer', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(upload_to='credentials/static/img'),
        ),
    ]
