# Generated by Django 2.1.5 on 2019-01-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='social_icon',
            field=models.CharField(default='fa-fa-icon', max_length=50),
        ),
    ]
