# Generated by Django 2.1.5 on 2019-02-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0007_auto_20190128_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='resume',
            field=models.FileField(default='Arnold_Resume.pdf', upload_to=''),
        ),
    ]
