# Generated by Django 2.1.5 on 2019-02-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0008_aboutme_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_code',
            field=models.CharField(default='https://github.com/apatten001', max_length=250),
        ),
    ]
